// <auto-generated />
using System;
using GetYoBike.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GetYoBike.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230426213645_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("GetYoBike.Server.Models.Bike", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Bikes");
                });

            modelBuilder.Entity("GetYoBike.Server.Models.Rent", b =>
                {
                    b.Property<string>("UserID")
                        .HasColumnType("TEXT");

                    b.Property<string>("BikeID")
                        .HasColumnType("TEXT");

                    b.Property<string>("CardCVC")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CardExpMonth")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CardExpYear")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CardNr")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RentHoursDuration")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RentStartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("RentedBikeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserID", "BikeID");

                    b.HasIndex("RentedBikeId");

                    b.ToTable("Rents");
                });

            modelBuilder.Entity("GetYoBike.Server.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("First_Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Last_Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GetYoBike.Server.Models.Rent", b =>
                {
                    b.HasOne("GetYoBike.Server.Models.Bike", "RentedBike")
                        .WithMany("Rents")
                        .HasForeignKey("RentedBikeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GetYoBike.Server.Models.User", "RenterUser")
                        .WithMany("Rents")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RentedBike");

                    b.Navigation("RenterUser");
                });

            modelBuilder.Entity("GetYoBike.Server.Models.Bike", b =>
                {
                    b.Navigation("Rents");
                });

            modelBuilder.Entity("GetYoBike.Server.Models.User", b =>
                {
                    b.Navigation("Rents");
                });
#pragma warning restore 612, 618
        }
    }
}
